### ISSUE TITLE
missing "=" sign for module metrics settings

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-module-ws#110]
```
alignak-backend-import --delete -b http://127.0.0.1:5000 -u=admin -p=admin /usr/local/etc/alignak/alignak.cfg
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
alignak-backend-import, version: 1.1.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Loading configuration for Alignak, version: 1.0.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Backend URL: http://127.0.0.1:5000
Dry-run mode (check only): False
Delete existing backend data: True
Updating backend data: False
Allowing duplicate objects: False
Default host location: {'type': 'Point', 'coordinates': [48.858293, 2.294601]}
Importing configuration: ['/usr/local/etc/alignak/alignak.cfg']
Loading daemon configuration file (None)...
No daemon configuration file specified, using defaults parameters
[2018-03-29 14:38:00 CEST] INFO: [alignak.module.backend_arbiter] Alignak backend importation script is active.
[2018-03-29 14:38:00 CEST] INFO: [alignak.module.backend_arbiter] Number of processes used by backend client: 1
[2018-03-29 14:38:00 CEST] ERROR: [alignak.modulesmanager] The module backend_arbiter raised an exception on loading, I remove it!
[2018-03-29 14:38:00 CEST] ERROR: [alignak.modulesmanager] Exception: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/modulesmanager.py", line 253, in get_instances
    instance = python_module.get_instance(alignak_module)
  File "/usr/local/lib/python2.7/dist-packages/alignak_module_backend/arbiter/module.py", line 63, in get_instance
    return AlignakBackendArbiter(mod_conf)
  File "/usr/local/lib/python2.7/dist-packages/alignak_module_backend/arbiter/module.py", line 103, in __init__
    int(getattr(mod_conf, 'statsd_port', '8125')),
ValueError: invalid literal for int() with base 10: ''
[2018-03-29 14:38:00 CEST] ERROR: [alignak.daemon] Errors were encountered when checking and loading modules:
[2018-03-29 14:38:00 CEST] ERROR: [alignak.daemon] The module backend_arbiter raised an exception on loading: invalid literal for int() with base 10: '', I remove it!
Elapsed time after Arbiter has loaded the configuration: 0.98641204834
Authenticating to the backend...
Access denied!
~~~~~~~~~~~~~~~~~~~~~~~~~~
Exiting with error code: 2

```

/usr/local/etc/alignak/arbiter/modules/mod-ws.cfg
```
## Module:      Web services
## Loaded by:   Receiver

# Get information about Alignak and remote command Alignak
define module {
    module_alias            web-services
    module_types            web-services
    python_name             alignak_module_ws

    # Module log level (DEBUG, INFO, WARNING, ERROR)
    log_level               INFO

...

    # Export module metrics to a statsd server.
    # By default at localhost:8125 (UDP) with the alignak prefix
    # Use the same prefix as the one defined in alignak (if any...)
    # Stats will be available in statsd_prefix.module_alias
    statsd_host=127.0.0.1
    statsd_port=8125
    statsd_prefix alignak.modules
    # Default is not enabled
    statsd_enabled=1
}
...

**Comment by mohierf** [comment]
Because this file is a cfg one, you must not use any equal sign! As such:
```
    statsd_host     127.0.0.1
    statsd_port     8125
    statsd_prefix alignak.modules
    # Default is not enabled
    statsd_enabled    1
```
