### ISSUE TITLE
Exception for livestate

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-ws#38]
On a specfic test case, an exception was raised:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_ws/utils/ws_server.py", line 278, in host
    return self.app.updateHost(host_name, data)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_ws/ws.py", line 565, in updateHost
    data.pop('livestate')
KeyError: 'livestate'
```

**Comment by mohierf** [comment]
Hmmm.... this happens when the host data are changed AND the livestate is updated in the same request
