### ISSUE TITLE
Error on host creation because of missing _realm

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-ws#64]
When an host must be created because it does not exist in the Alignak backend, an internal server error is raised:
```
alignak@Alignak-VirtualBox:~/alignak-module-ws/tools$ ./customs.sh 
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_ws/utils/ws_server.py", line 286, in host
    return self.app.updateHost(name, data)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_ws/ws.py", line 568, in updateHost
    post_data = self.backendCreationData(host_name, None, data['template'])
  File "/usr/local/lib/python2.7/site-packages/alignak_module_ws/ws.py", line 371, in backendCreationData
    post_data.update({'_realm': self.default_realm['_id']})
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>
      </span>
    </div>
    </body>
</html>

```

**Comment by mohierf** [comment]
This is because the WS module default_realm is not defined.
